version: '3.5'
services:
  postgres:
    image: 'postgres:11'
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
  app:
    image: 'blan:latest'
    build:
      context: .
    restart: unless-stopped
    ports:
      - '8081:8081'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: test
